apiVersion: v2
name: secrets-configuration-aws
description: A Helm chart to configure secrets for the Snicket Labs platform. Depends on EKS ASCP and AWS Secrets Manager.
type: application
version: 0.2.0
