apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ascp.spcName" (dict "root" $ "component" "api") }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "{{ .Values.apiSecretName }}"
          objectType: "secretsmanager"
          jmesPath:
          - path: "api_secret_key_base"
            objectAlias: "api_secret_key_base"
          - path: "secret_key_base"
            objectAlias: "secret_key_base"
          - path: "ingest_credential_encryption_key"
            objectAlias: "ingest_credential_encryption_key"
  secretObjects:
    - secretName: "{{ .Values.k8sSecretNames.api }}"
      type: Opaque
      data:
        - key: api_secret_key_base
          objectName: api_secret_key_base
        - key: secret_key_base
          objectName: secret_key_base
        - key: ingest_credential_encryption_key
          objectName: ingest_credential_encryption_key
