## this relies on the dockerSecretName secret existing in AWS Secrets Manager
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ascp.spcName" (dict "root" $ "component" "docker") }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws                             
  parameters: 
    objects: |
        - objectName: "{{ .Values.dockerSecretName }}"
          objectType: "secretsmanager"
  secretObjects:
    - secretName: "{{ .Values.k8sSecretNames.docker }}"
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: "{{ .Values.dockerSecretName }}"
          key: ".dockerconfigjson"