## this relies on the honeybadgerSecretName secret existing in AWS Secrets Manager
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ascp.spcName" (dict "root" $ "component" "honeybadger") }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.honeybadgerSecretName }}"
        objectType: "secretsmanager"
        objectAlias: "honeybadger"
  secretObjects:
    - secretName: "{{ .Values.k8sSecretNames.honeybadger }}"
      type: Opaque
      data:
        - objectName: "honeybadger"
          key: "apiKey"
