apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ascp.spcName" (dict "root" $ "component" "owning-user-credentials") }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "{{ .Values.userSecretName }}"
          objectType: "secretsmanager"
          jmesPath:
          - path: "password"
            objectAlias: "password"
  secretObjects:
    - secretName: "{{ .Values.k8sSecretNames.user }}"
      type: Opaque
      data:
        - key: password
          objectName: password


