{{- if .Values.smtp.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ascp.spcName" (dict "root" $ "component" "smtp") }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.smtp.smtpSecretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "smtp_address"
            objectAlias: "SMTP_ADDRESS"
          - path: "smtp_port"
            objectAlias: "SMTP_PORT"
          - path: "smtp_user_name"
            objectAlias: "SMTP_USER_NAME"
          - path: "smtp_password"
            objectAlias: "SMTP_PASSWORD"
          - path: "smtp_domain"
            objectAlias: "SMTP_DOMAIN"
          - path: "mailer_default_from"
            objectAlias: "MAILER_DEFAULT_FROM"
  secretObjects:
    - secretName: "{{ .Values.smtp.k8sSecretName }}"
      type: Opaque
      data:
        - objectName: "SMTP_ADDRESS"
          key: SMTP_ADDRESS
        - objectName: "SMTP_PORT"
          key: SMTP_PORT
        - objectName: "SMTP_USER_NAME"
          key: SMTP_USER_NAME
        - objectName: "SMTP_PASSWORD"
          key: SMTP_PASSWORD
        - objectName: "SMTP_DOMAIN"
          key: SMTP_DOMAIN
        - objectName: "MAILER_DEFAULT_FROM"
          key: MAILER_DEFAULT_FROM
{{- end }}