apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.k8sSecretNames.api }}
    creationPolicy: Owner
  data:
    - secretKey: secret_key_base
      remoteRef: { key: {{ .Values.secretNames.api }}, property: secret_key_base }
    - secretKey: api_secret_key_base
      remoteRef: { key: {{ .Values.secretNames.api }}, property: api_secret_key_base }
    - secretKey: ingest_credential_encryption_key
      remoteRef: { key: {{ .Values.secretNames.api }}, property: ingest_credential_encryption_key }
