apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: honeybadger-api-key
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.k8sSecretNames.honeybadger }}
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: {{ .Values.secretNames.honeybadger }}
