apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.k8sSecretNames.rdsPg }}
    creationPolicy: Owner
  data:
    - secretKey: db_name
      remoteRef: { key: {{ .Values.secretNames.cloudSql }}, property: dbname }
    - secretKey: host
      remoteRef: { key: {{ .Values.secretNames.cloudSql }}, property: host }
    - secretKey: password
      remoteRef: { key: {{ .Values.secretNames.cloudSql }}, property: password }
    - secretKey: port
      remoteRef: { key: {{ .Values.secretNames.cloudSql }}, property: port }
    - secretKey: username
      remoteRef: { key: {{ .Values.secretNames.cloudSql }}, property: username }
