apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: owning-user-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.k8sSecretNames.user }}
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef: { key: {{ .Values.secretNames.user }}, property: password }
