{{- if .Values.smtp.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.smtp.k8sSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: SMTP_ADDRESS
      remoteRef: { key: {{ .Values.smtp.secretName }}, property: smtp_address }
    - secretKey: SMTP_PORT
      remoteRef: { key: {{ .Values.smtp.secretName }}, property: smtp_port }
    - secretKey: SMTP_USER_NAME
      remoteRef: { key: {{ .Values.smtp.secretName }}, property: smtp_user_name }
    - secretKey: SMTP_PASSWORD
      remoteRef: { key: {{ .Values.smtp.secretName }}, property: smtp_password }
    - secretKey: SMTP_DOMAIN
      remoteRef: { key: {{ .Values.smtp.secretName }}, property: smtp_domain }
    - secretKey: MAILER_DEFAULT_FROM
      remoteRef: { key: {{ .Values.smtp.secretName }}, property: mailer_default_from }
{{- end }}
