apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.k8sSecretNames.redis | default (printf "%s-redis" .Values.clusterName) }}
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef: { key: {{ .Values.secretNames.redis }}, property: url }
    - secretKey: endpoint
      remoteRef: { key: {{ .Values.secretNames.redis }}, property: host }
    - secretKey: elasticache_url
      remoteRef: { key: {{ .Values.secretNames.redis }}, property: url }
    - secretKey: password
      remoteRef: { key: {{ .Values.secretNames.redis }}, property: auth }
