apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    {{- toYaml .Values.secretStore.provider | nindent 4 }}
